name: perslm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
    - transformers>=4.36.0
    - datasets
    - accelerate
    - deepspeed
    - vllm
    - faiss-cpu
    - wandb
    - tqdm
    - numpy
    - pandas
    - scikit-learn
    - black
    - isort
    - flake8
    - pytest 