'use client'

import React from 'react'
import { TaskMonitorProvider } from '@/components/TaskMonitorProvider'
import { PersLMTaskMonitor } from '@/components/PersLMTaskMonitor'

// V0 UI Task Monitor Page
export default function TaskMonitorV0Page() {
  // Sample tasks for the V0 UI
  const v0Tasks = [
    { 
      description: 'Implement V0 UI integration', 
      status: 'completed' as const,
      tags: ['UI', 'Integration'],
      priority: 'high' as const 
    },
    { 
      description: 'Setup route structure', 
      status: 'completed' as const,
      tags: ['Infrastructure'],
      priority: 'high' as const 
    },
    { 
      description: 'Create shared components', 
      status: 'in-progress' as const,
      tags: ['UI', 'Components'],
      priority: 'medium' as const 
    },
    { 
      description: 'Implement responsive design', 
      status: 'pending' as const,
      tags: ['UI', 'Responsive'],
      priority: 'medium' as const 
    },
    { 
      description: 'Add analytics tracking', 
      status: 'pending' as const,
      tags: ['Analytics'],
      priority: 'low' as const 
    }
  ];

  return (
    <div className="container mx-auto py-8 px-4">
      <div className="flex flex-col space-y-6">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold">PersLM Task Monitor (V0)</h1>
          <div className="text-sm text-gray-500">V0-generated UI</div>
        </div>
        
        <div className="bg-blue-50 p-6 rounded-lg border border-blue-100 mb-4">
          <h2 className="text-xl font-semibold text-blue-800 mb-2">V0 UI Integration</h2>
          <p className="text-blue-700 mb-4">
            This is the integrated V0 UI version of the Task Monitor. It uses the same core functionality
            but with a different UI approach generated by the V0 model.
          </p>
        </div>
        
        <TaskMonitorProvider persistKey="perslm-v0">
          <PersLMTaskMonitor defaultTasks={v0Tasks} />
        </TaskMonitorProvider>
      </div>
    </div>
  )
} 