# Personalization Configuration

# User Profile Settings
user_profile:
  storage:
    type: "json"  # Options: json, memory, database
    path: "data/profiles"
  inference:
    enabled: true
    confidence_threshold: 0.6  # Minimum confidence for inferred preferences
    update_frequency: 5  # Update after every N interactions

# Adaptation Settings
adaptation:
  strategies:
    content_personalization:
      enabled: true
      weight: 0.7
      min_confidence: 0.6
    style_adaptation:
      enabled: true
      weight: 0.6
      min_confidence: 0.7
    complexity_adaptation:
      enabled: true
      weight: 0.8
      min_confidence: 0.5
    interest_prioritization:
      enabled: true
      weight: 0.7
      min_confidence: 0.6
    context_awareness:
      enabled: true
      weight: 0.9
      min_confidence: 0.5
  feedback:
    enabled: true
    auto_adjust: true
    adjustment_rate: 0.1  # Maximum adjustment per feedback
  
# Context Settings
context:
  collection:
    time_of_day: true
    device_info: true
    location: 
      enabled: false  # Disabled by default for privacy
      precision: "country"  # Options: country, region, city
    session_data: true
  refresh_rate: 300  # Seconds between context refreshes

# Memory Integration
memory:
  max_interactions: 1000  # Maximum interactions to store
  relevance_threshold: 0.7  # Minimum relevance score for memory retrieval
  recency_weight: 0.4  # Weight given to recency vs. semantic relevance 